### ISSUE TITLE
Seleccionar lista de blogs

### ISSUE THREAD

**Issue by ernesto-butto** [poolebu/ebookme#68]
- [x] Seths blog
- [x] Tim ferris
- [x] Humans in New York
- [x] Maria popova's https://www.brainpickings.org
- [x] See naval tim episode links, might have something

**Comment by ernesto-butto** [comment]
# Maria popova's https://www.brainpickings.org

### Friedrich Nietzsche on Why a Fulfilling Life Requires Embracing Rather than Running from Difficulty

https://www.brainpickings.org/2014/10/15/nietzsche-on-difficulty/

### An Antidote to the Age of Anxiety: Alan Watts on Happiness and How to Live with Presence

https://www.brainpickings.org/2014/01/06/alan-watts-wisdom-of-insecurity-1/

### Fixed vs. Growth: The Two Basic Mindsets That Shape Our Lives

https://www.brainpickings.org/2014/01/29/carol-dweck-mindset/

### How to Love: Legendary Zen Buddhist Teacher Thich Nhat Hanh on Mastering the Art of “Interbeing”

https://www.brainpickings.org/2015/03/31/how-to-love-thich-nhat-hanh/

### Leisure, the Basis of Culture: An Obscure German Philosopher’s Timely 1948 Manifesto for Reclaiming Our Human Dignity in a Culture of Workaholism

https://www.brainpickings.org/2015/08/10/leisure-the-basis-of-culture-josef-pieper/

# Humans of New York

http://thenectarcollective.com/best-humans-of-new-york/

# Tim Ferris

### The Not-To-Do List: 9 Habits to Stop Now

http://fourhourworkweek.com/2007/08/16/the-not-to-do-list-9-habits-to-stop-now/

### How to Use Philosophy as a Personal Operating System: From Seneca to Musashi

http://fourhourworkweek.com/2011/05/18/philosophy-as-a-personal-operating-system-from-seneca-to-musashi/

### You Are What You Read: 14 Thought Leaders Share Their Bookshelves

http://fourhourworkweek.com/2013/10/21/you-are-what-you-read-14-thought-leaders-share-their-bookshelves/

### You Are What You Read: 14 Thought Leaders Share Their Bookshelves

http://fourhourworkweek.com/2013/10/21/you-are-what-you-read-14-thought-leaders-share-their-bookshelves/

### How to Create a Million-Dollar Business This Weekend

http://fourhourworkweek.com/2011/09/24/how-to-create-a-million-dollar-business-this-weekend-examples-appsumo-mint-chihuahuas/

### Hacking Kickstarter: How to Raise $100,000 in 10 Days

http://fourhourworkweek.com/2012/12/18/hacking-kickstarter-how-to-raise-100000-in-10-days-includes-successful-templates-e-mails-etc/

### How to Lose 20 lbs. of Fat in 30 Days… Without Doing Any Exercise

http://fourhourworkweek.com/2007/04/06/how-to-lose-20-lbs-of-fat-in-30-days-without-doing-any-exercise/

# Seth: Make things happen

### The future of the library

http://sethgodin.typepad.com/seths_blog/2011/05/the-future-of-the-library.html

### Fear of bad ideas

http://sethgodin.typepad.com/seths_blog/2009/12/fear-of-bad-ideas.html

### Reject the tyranny of being picked: pick yourself

http://sethgodin.typepad.com/seths_blog/2011/03/reject-the-tyranny-of-being-picked-pick-yourself.html

### What investors want

http://sethgodin.typepad.com/seths_blog/2016/02/what-investors-want.html

### The triumph of coal marketing

http://sethgodin.typepad.com/seths_blog/2011/03/the-triumph-of-coal-marketing.html

**Comment by poolebu** [comment]
# Personhood: A Game for Two or More Players
Kevin Simler
http://www.meltingasphalt.com/personhood-a-game-for-two-or-more-players/

# Maria popova's https://www.brainpickings.org

### Friedrich Nietzsche on Why a Fulfilling Life Requires Embracing Rather than Running from Difficulty

https://www.brainpickings.org/2014/10/15/nietzsche-on-difficulty/

### An Antidote to the Age of Anxiety: Alan Watts on Happiness and How to Live with Presence

https://www.brainpickings.org/2014/01/06/alan-watts-wisdom-of-insecurity-1/

### Fixed vs. Growth: The Two Basic Mindsets That Shape Our Lives
https://www.brainpickings.org/2014/01/29/carol-dweck-mindset/

### How to Love: Legendary Zen Buddhist Teacher Thich Nhat Hanh on Mastering the Art of “Interbeing”

https://www.brainpickings.org/2015/03/31/how-to-love-thich-nhat-hanh/

### Leisure, the Basis of Culture: An Obscure German Philosopher’s Timely 1948 Manifesto for Reclaiming Our Human Dignity in a Culture of Workaholism

https://www.brainpickings.org/2015/08/10/leisure-the-basis-of-culture-josef-pieper/

# Humans of New York

http://thenectarcollective.com/best-humans-of-new-york/

# Tim Ferris

### The Not-To-Do List: 9 Habits to Stop Now

http://fourhourworkweek.com/2007/08/16/the-not-to-do-list-9-habits-to-stop-now/

### How to Use Philosophy as a Personal Operating System: From Seneca to Musashi

http://fourhourworkweek.com/2011/05/18/philosophy-as-a-personal-operating-system-from-seneca-to-musashi/

### You Are What You Read: 14 Thought Leaders Share Their Bookshelves

http://fourhourworkweek.com/2013/10/21/you-are-what-you-read-14-thought-leaders-share-their-bookshelves/


### You Are What You Read: 14 Thought Leaders Share Their Bookshelves

http://fourhourworkweek.com/2013/10/21/you-are-what-you-read-14-thought-leaders-share-their-bookshelves/

### How to Create a Million-Dollar Business This Weekend

http://fourhourworkweek.com/2011/09/24/how-to-create-a-million-dollar-business-this-weekend-examples-appsumo-mint-chihuahuas/

### Hacking Kickstarter: How to Raise $100,000 in 10 Days

http://fourhourworkweek.com/2012/12/18/hacking-kickstarter-how-to-raise-100000-in-10-days-includes-successful-templates-e-mails-etc/

### How to Lose 20 lbs. of Fat in 30 Days… Without Doing Any Exercise

http://fourhourworkweek.com/2007/04/06/how-to-lose-20-lbs-of-fat-in-30-days-without-doing-any-exercise/


# Seth: Make things happen

### The future of the library

http://sethgodin.typepad.com/seths_blog/2011/05/the-future-of-the-library.html

### Fear of bad ideas

http://sethgodin.typepad.com/seths_blog/2009/12/fear-of-bad-ideas.html

### Reject the tyranny of being picked: pick yourself

http://sethgodin.typepad.com/seths_blog/2011/03/reject-the-tyranny-of-being-picked-pick-yourself.html

### What investors want

http://sethgodin.typepad.com/seths_blog/2016/02/what-investors-want.html

### The triumph of coal marketing 

http://sethgodin.typepad.com/seths_blog/2011/03/the-triumph-of-coal-marketing.html
